import type { Achievement } from "@/types";

export const achievements: Achievement[] = [
  {
    id: "first-letter",
    title: "First Letter!",
    teluguTitle: "మొదటి అక్షరం!",
    description: "Learned your first Telugu letter",
    icon: "🌟",
    xpReward: 10,
    condition: { type: "letters_learned", count: 1 },
  },
  {
    id: "vowel-master",
    title: "Vowel Master",
    teluguTitle: "అచ్చుల నిపుణుడు",
    description: "Learned all 8 vowels",
    icon: "🏆",
    xpReward: 100,
    condition: { type: "vowels_complete", count: 8 },
  },
  {
    id: "first-word",
    title: "Word Wizard",
    teluguTitle: "పదాల మాంత్రికుడు",
    description: "Read your first Telugu word",
    icon: "📖",
    xpReward: 25,
    condition: { type: "words_read", count: 1 },
  },
  {
    id: "five-streak",
    title: "On Fire!",
    teluguTitle: "అద్భుతం!",
    description: "5 correct answers in a row",
    icon: "🔥",
    xpReward: 50,
    condition: { type: "streak", count: 5 },
  },
  {
    id: "ten-lessons",
    title: "Dedicated Learner",
    teluguTitle: "నిబద్ధ విద్యార్థి",
    description: "Completed 10 lessons",
    icon: "📚",
    xpReward: 75,
    condition: { type: "lessons_complete", count: 10 },
  },
  {
    id: "first-story",
    title: "Story Time",
    teluguTitle: "కథా సమయం",
    description: "Read your first Telugu story",
    icon: "📕",
    xpReward: 100,
    condition: { type: "stories_read", count: 1 },
  },
  {
    id: "consonant-starter",
    title: "Consonant Explorer",
    teluguTitle: "హల్లుల అన్వేషకుడు",
    description: "Learned your first 5 consonants",
    icon: "🔤",
    xpReward: 50,
    condition: { type: "consonants_learned", count: 5 },
  },
  {
    id: "perfect-lesson",
    title: "Perfect Score!",
    teluguTitle: "పర్ఫెక్ట్!",
    description: "Completed a lesson with no mistakes",
    icon: "💯",
    xpReward: 30,
    condition: { type: "perfect_lesson", count: 1 },
  },
];
