import type { ConsonantData } from "@/types";

export const consonants: ConsonantData[] = [
  {
    id: "ka",
    telugu: "క",
    transliteration: "ka",
    englishHint: "Like 'k' in 'kite'",
    mnemonic: "Think of a 'kite' flying",
    audioUrl: "/audio/consonants/ka.mp3",
    group: "ka-group",
  },
  {
    id: "kha",
    telugu: "ఖ",
    transliteration: "kha",
    englishHint: "Like 'kh' with extra breath",
    mnemonic: "Aspirated 'k' - like breathing out",
    audioUrl: "/audio/consonants/kha.mp3",
    group: "ka-group",
  },
  {
    id: "ga",
    telugu: "గ",
    transliteration: "ga",
    englishHint: "Like 'g' in 'go'",
    mnemonic: "Think of 'go' or 'game'",
    audioUrl: "/audio/consonants/ga.mp3",
    group: "ka-group",
  },
  {
    id: "gha",
    telugu: "ఘ",
    transliteration: "gha",
    englishHint: "Like 'gh' with extra breath",
    mnemonic: "Aspirated 'g' - heavier sound",
    audioUrl: "/audio/consonants/gha.mp3",
    group: "ka-group",
  },
  {
    id: "nga",
    telugu: "ఙ",
    transliteration: "nga",
    englishHint: "Like 'ng' in 'ring'",
    mnemonic: "Nasal 'ng' sound",
    audioUrl: "/audio/consonants/nga.mp3",
    group: "ka-group",
  },
  {
    id: "cha",
    telugu: "చ",
    transliteration: "cha",
    englishHint: "Like 'ch' in 'chair'",
    mnemonic: "Think of 'chair' or 'cheese'",
    audioUrl: "/audio/consonants/cha.mp3",
    group: "cha-group",
  },
  {
    id: "chha",
    telugu: "ఛ",
    transliteration: "chha",
    englishHint: "Like 'chh' with extra breath",
    mnemonic: "Aspirated 'ch' sound",
    audioUrl: "/audio/consonants/chha.mp3",
    group: "cha-group",
  },
  {
    id: "ja",
    telugu: "జ",
    transliteration: "ja",
    englishHint: "Like 'j' in 'jump'",
    mnemonic: "Think of 'jump' or 'joy'",
    audioUrl: "/audio/consonants/ja.mp3",
    group: "cha-group",
  },
  {
    id: "jha",
    telugu: "ఝ",
    transliteration: "jha",
    englishHint: "Like 'jh' with extra breath",
    mnemonic: "Aspirated 'j' sound",
    audioUrl: "/audio/consonants/jha.mp3",
    group: "cha-group",
  },
  {
    id: "nya",
    telugu: "ఞ",
    transliteration: "nya",
    englishHint: "Like 'ny' in 'canyon'",
    mnemonic: "Nasal 'ny' sound",
    audioUrl: "/audio/consonants/nya.mp3",
    group: "cha-group",
  },
];
