export interface Proverb {
  id: string;
  te: string;
  trans: string;
  en: string;
  meaning: { te: string; en: string };
  usage: string;
  emoji: string;
}

export const TELUGU_PROVERBS: Proverb[] = [
  {
    id: "p1",
    te: "ఆకలి రుచి ఎరుగదు",
    trans: "AAKALI RUCHI ERUGADU",
    en: "Hunger knows no taste",
    meaning: { te: "ఆకలి వేస్తే ఏది తిన్నా బాగుంటుంది", en: "When you're very hungry, everything tastes good" },
    usage: "When someone eats food they usually don't like because they're hungry",
    emoji: "🍽️",
  },
  {
    id: "p2",
    te: "చేతిలో వెన్న ఉంచుకొని నెయ్యి కోసం వెతికినట్లు",
    trans: "CHETHILO VENNA UNCHUKONI NEYYI KOSAM VETIKINATLU",
    en: "Having butter in hand but searching for ghee",
    meaning: { te: "ఉన్నదానితో సంతోషపడకుండా లేనిదాని కోసం వెతకడం", en: "Not being happy with what you have and searching for what you don't" },
    usage: "When someone ignores what's right in front of them",
    emoji: "🧈",
  },
  {
    id: "p3",
    te: "అడగని వరం లేదు",
    trans: "ADAGANI VARAM LEDU",
    en: "There's no gift without asking",
    meaning: { te: "అడిగితేనే దొరుకుతుంది", en: "You only get things if you ask for them" },
    usage: "Encouraging someone to speak up and ask for what they need",
    emoji: "🙋",
  },
  {
    id: "p4",
    te: "ఓడలు బండ్లు బండ్లు ఓడలు",
    trans: "ODALU BANDLU BANDLU ODALU",
    en: "Ships become carts, carts become ships",
    meaning: { te: "కాలం మారుతుంది — అదృష్టం తిరుగుతుంది", en: "Times change — fortunes reverse" },
    usage: "When someone who was rich becomes poor or vice versa",
    emoji: "🚢",
  },
  {
    id: "p5",
    te: "నేర్చుకోవడం ఎప్పుడూ ఆలస్యం కాదు",
    trans: "NERCHUKOVADAM EPPUDOO AALASYAM KAADU",
    en: "It's never too late to learn",
    meaning: { te: "ఏ వయసైనా నేర్చుకోవచ్చు", en: "You can learn at any age" },
    usage: "Encouraging someone who thinks they're too old to try something new",
    emoji: "📚",
  },
  {
    id: "p6",
    te: "ఆకు రాలితే చెట్టుకు నష్టం",
    trans: "AAKU RAALICHE CHETTUKU NASHTAM",
    en: "When a leaf falls, the tree suffers",
    meaning: { te: "ఎవరు పోయినా ఆ కుటుంబానికి బాధ", en: "When someone leaves, the family feels the loss" },
    usage: "When a family member goes away",
    emoji: "🍂",
  },
  {
    id: "p7",
    te: "అన్నం పెట్టే చేతిని కొరికే కుక్క లాగా",
    trans: "ANNAM PETTE CHETHINI KORIKE KUKKA LAAGAA",
    en: "Like a dog that bites the hand that feeds it",
    meaning: { te: "సహాయం చేసిన వారికి హాని చేయడం", en: "Harming someone who helps you" },
    usage: "When someone is ungrateful",
    emoji: "🐕",
  },
  {
    id: "p8",
    te: "చెట్టు ఫలాలతో తెలుస్తుంది",
    trans: "CHETTU PHALAALATHO THELUSTUNDI",
    en: "A tree is known by its fruits",
    meaning: { te: "మనిషి పనులతో తెలుస్తాడు", en: "A person is known by their actions" },
    usage: "Judging someone by what they do, not what they say",
    emoji: "🌳",
  },
  {
    id: "p9",
    te: "నీళ్ళు లేకుండా చేప బతకదు",
    trans: "NEELLU LEKUNDA CHEPA BATHAKADU",
    en: "A fish can't live without water",
    meaning: { te: "ప్రతి ఒక్కరికి తమ వాతావరణం అవసరం", en: "Everyone needs their own environment to thrive" },
    usage: "When someone is out of their comfort zone",
    emoji: "🐟",
  },
  {
    id: "p10",
    te: "ఐకమత్యమే మహాబలం",
    trans: "AIKAMATHYAME MAHAABALAM",
    en: "Unity is great strength",
    meaning: { te: "కలిసి ఉంటే బలం పెరుగుతుంది", en: "When you stay together, strength increases" },
    usage: "When a team works together to solve a problem",
    emoji: "🤝",
  },
  {
    id: "p11",
    te: "వినాశకాలే విపరీత బుద్ధి",
    trans: "VINAASHAKAALE VIPAREETHA BUDDHI",
    en: "When ruin approaches, wisdom reverses",
    meaning: { te: "చెడు కాలం వస్తే తెలివి పోతుంది", en: "Before downfall, judgment fails" },
    usage: "When someone makes terrible decisions that lead to their failure",
    emoji: "⚡",
  },
  {
    id: "p12",
    te: "చదువు మొదటి మెట్టు",
    trans: "CHADUVU MODATI METTU",
    en: "Education is the first step",
    meaning: { te: "విద్య అన్నింటికి మూలం", en: "Education is the foundation of everything" },
    usage: "Encouraging children to study",
    emoji: "📖",
  },
  {
    id: "p13",
    te: "మీసాలకు సంపెంగ నూనె",
    trans: "MEESAALAKU SAMPENGA NOONE",
    en: "Champaca oil for mustache",
    meaning: { te: "చేతకాని వాడికి హోదా లేదు", en: "Showing off beyond one's means" },
    usage: "When someone pretends to be richer than they are",
    emoji: "💈",
  },
  {
    id: "p14",
    te: "పది మంది ఒకటిగా ఉంటే పాపం పారిపోతుంది",
    trans: "PADHI MANDI OKATIGAA UNTE PAAPAM PAARIPOTHUNDI",
    en: "When ten people are united, evil runs away",
    meaning: { te: "ఐకమత్యం ఉంటే ఏ కష్టాన్ని అయినా తట్టుకోవచ్చు", en: "Unity can overcome any hardship" },
    usage: "When community comes together to solve a problem",
    emoji: "👥",
  },
  {
    id: "p15",
    te: "తప్పు చేసి దాచలేం — పూలు పూస్తే వాసన వస్తుంది",
    trans: "THAPPU CHESI DAACHLEM — POOLU POOSTHE VAASANA VASTHUNDI",
    en: "Can't hide a mistake — flowers bloom and fragrance comes",
    meaning: { te: "తప్పు చేస్తే ఎప్పుడో బయటపడుతుంది", en: "Truth always comes out eventually" },
    usage: "When someone tries to hide a lie",
    emoji: "🌹",
  },
  {
    id: "p16",
    te: "పిల్లి కళ్ళు మూసుకొని పాలు తాగితే ఎవరూ చూడరా",
    trans: "PILLI KALLLU MOOSUKONI PAALU THAGITHE EVAROO CHOODARA",
    en: "If a cat closes its eyes while drinking milk, will no one see?",
    meaning: { te: "తప్పు చేస్తూ ఎవరూ చూడరని అనుకోవడం", en: "Fooling yourself into thinking no one notices" },
    usage: "When someone does something wrong thinking they won't get caught",
    emoji: "🐱",
  },
  {
    id: "p17",
    te: "నోరు మంచిది అయితే ఊరు మంచిది",
    trans: "NORU MANCHIDI AITHE OORU MANCHIDI",
    en: "If your speech is good, the village is good",
    meaning: { te: "మంచిగా మాట్లాడితే అందరూ స్నేహంగా ఉంటారు", en: "Speak kindly and everyone will be your friend" },
    usage: "Teaching children to speak politely",
    emoji: "🗣️",
  },
  {
    id: "p18",
    te: "ఆశ ఉండాలి అత్యాశ ఉండకూడదు",
    trans: "AASHA UNDAALI ATHYAASHA UNDAKOODADU",
    en: "Have hope, but don't be greedy",
    meaning: { te: "కోరికలు మంచివే, అత్యాశ మంచిది కాదు", en: "Desires are fine, greed is not" },
    usage: "When someone wants too much",
    emoji: "⚖️",
  },
  {
    id: "p19",
    te: "పంచుకుంటే ప్రేమ పెరుగుతుంది",
    trans: "PANCHUKUNTE PREMA PERUGUTHUNDI",
    en: "Sharing increases love",
    meaning: { te: "ఇంకొకళ్ళతో పంచుకోవడం వల్ల ఆనందం పెరుగుతుంది", en: "Sharing with others multiplies happiness" },
    usage: "Teaching children to share",
    emoji: "💝",
  },
  {
    id: "p20",
    te: "అమ్మ మాట — ఆణిముత్యం",
    trans: "AMMA MAATA — AANIMUTHYAM",
    en: "Mother's word is a pearl",
    meaning: { te: "అమ్మ చెప్పేది ఎప్పుడూ విలువైనది", en: "A mother's advice is always precious" },
    usage: "Reminding children to listen to their parents",
    emoji: "👩",
  },
];
