import type { VowelPair } from "@/types";

export const vowels: VowelPair[] = [
  {
    id: "a",
    telugu: "అ",
    transliteration: "a",
    englishHint: "Like 'u' in 'cup'",
    mnemonic: "Think of saying 'Ah!' when surprised",
    audioUrl: "/audio/vowels/a.mp3",
    anchorWord: "అమ్మ",
    anchorTransliteration: "AMMA",
    anchorMeaning: "Mother",
    anchorEmoji: "👩",
    anchorImage: "/images/anchors/a.png",
  },
  {
    id: "aa",
    telugu: "ఆ",
    transliteration: "aa",
    englishHint: "Like 'a' in 'father'",
    mnemonic: "Longer 'Aaa' like at the doctor",
    audioUrl: "/audio/vowels/aa.mp3",
    anchorWord: "ఆవు",
    anchorTransliteration: "AAVU",
    anchorMeaning: "Cow",
    anchorEmoji: "🐄",
    anchorImage: "/images/anchors/aa.png",
  },
  {
    id: "i",
    telugu: "ఇ",
    transliteration: "i",
    englishHint: "Like 'i' in 'bit'",
    mnemonic: "Short 'i' like 'is'",
    audioUrl: "/audio/vowels/i.mp3",
    anchorWord: "ఇల్లు",
    anchorTransliteration: "ILLU",
    anchorMeaning: "House",
    anchorEmoji: "🏠",
    anchorImage: "/images/anchors/i.png",
  },
  {
    id: "ee",
    telugu: "ఈ",
    transliteration: "ee",
    englishHint: "Like 'ee' in 'feet'",
    mnemonic: "Long 'ee' like 'cheese'",
    audioUrl: "/audio/vowels/ii.mp3",
    anchorWord: "ఈగ",
    anchorTransliteration: "EEGA",
    anchorMeaning: "Fly",
    anchorEmoji: "🪰",
    anchorImage: "/images/anchors/ii.png",
  },
  {
    id: "u",
    telugu: "ఉ",
    transliteration: "u",
    englishHint: "Like 'u' in 'put'",
    mnemonic: "Short 'oo' like 'book'",
    audioUrl: "/audio/vowels/u.mp3",
    anchorWord: "ఉంగరం",
    anchorTransliteration: "UNGARAM",
    anchorMeaning: "Ring",
    anchorEmoji: "💍",
    anchorImage: "/images/anchors/u.png",
  },
  {
    id: "oo",
    telugu: "ఊ",
    transliteration: "oo",
    englishHint: "Like 'oo' in 'boot'",
    mnemonic: "Long 'oo' like 'moon'",
    audioUrl: "/audio/vowels/uu.mp3",
    anchorWord: "ఊయల",
    anchorTransliteration: "OOYALA",
    anchorMeaning: "Swing",
    anchorEmoji: "🎠",
    anchorImage: "/images/anchors/uu.png",
  },
  {
    id: "ru",
    telugu: "ఋ",
    transliteration: "ru",
    englishHint: "Like 'ri' in 'rig' (quickly)",
    mnemonic: "A quick 'ri' sound, like 'Krishna'",
    audioUrl: "/audio/vowels/ru.mp3",
    anchorWord: "ఋషి",
    anchorTransliteration: "RUSHI",
    anchorMeaning: "Sage",
    anchorEmoji: "🧘",
    anchorImage: "/images/anchors/ru.png",
  },
  {
    id: "roo",
    telugu: "ౠ",
    transliteration: "roo",
    englishHint: "Like a longer 'ri' sound",
    mnemonic: "Long version of ఋ — rare but royal!",
    audioUrl: "/audio/vowels/roo.mp3",
    anchorWord: "ౠ",
    anchorTransliteration: "ROO",
    anchorMeaning: "Long 'ru' sound (rare letter!)",
    anchorEmoji: "🐢",
    anchorImage: "/images/anchors/roo.png",
  },
  {
    id: "e",
    telugu: "ఎ",
    transliteration: "e",
    englishHint: "Like 'e' in 'get'",
    mnemonic: "Short 'e' like 'bed'",
    audioUrl: "/audio/vowels/e.mp3",
    anchorWord: "ఎలుక",
    anchorTransliteration: "ELUKA",
    anchorMeaning: "Mouse",
    anchorEmoji: "🐭",
    anchorImage: "/images/anchors/e.png",
  },
  {
    id: "ay",
    telugu: "ఏ",
    transliteration: "ay",
    englishHint: "Like 'ay' in 'day'",
    mnemonic: "Long 'ay' like 'day'",
    audioUrl: "/audio/vowels/ee.mp3",
    anchorWord: "ఏనుగు",
    anchorTransliteration: "ENUGU",
    anchorMeaning: "Elephant",
    anchorEmoji: "🐘",
    anchorImage: "/images/anchors/ee.png",
  },
  {
    id: "ai",
    telugu: "ఐ",
    transliteration: "ai",
    englishHint: "Like 'ai' in 'aisle'",
    mnemonic: "Say 'eye' — that's the sound!",
    audioUrl: "/audio/vowels/ai.mp3",
    anchorWord: "ఐస్ క్రీమ్",
    anchorTransliteration: "ICE CREAM",
    anchorMeaning: "Ice cream",
    anchorEmoji: "🍦",
    anchorImage: "/images/anchors/ai.png",
  },
  {
    id: "o",
    telugu: "ఒ",
    transliteration: "o",
    englishHint: "Like 'o' in 'go' (short)",
    mnemonic: "Short 'o' like 'oh!'",
    audioUrl: "/audio/vowels/o.mp3",
    anchorWord: "ఒంటె",
    anchorTransliteration: "ONTE",
    anchorMeaning: "Camel",
    anchorEmoji: "🐪",
    anchorImage: "/images/anchors/o.png",
  },
  {
    id: "oh",
    telugu: "ఓ",
    transliteration: "oh",
    englishHint: "Like 'o' in 'ocean'",
    mnemonic: "Long 'oh' like 'ocean'",
    audioUrl: "/audio/vowels/oo.mp3",
    anchorWord: "ఓడ",
    anchorTransliteration: "ODA",
    anchorMeaning: "Boat",
    anchorEmoji: "⛵",
    anchorImage: "/images/anchors/oo.png",
  },
  {
    id: "ow",
    telugu: "ఔ",
    transliteration: "ow",
    englishHint: "Like 'ow' in 'how'",
    mnemonic: "Say 'ow!' — that's the sound!",
    audioUrl: "/audio/vowels/au.mp3",
    anchorWord: "ఔషధం",
    anchorTransliteration: "AUSHADHAM",
    anchorMeaning: "Medicine",
    anchorEmoji: "💊",
    anchorImage: "/images/anchors/au.png",
  },
  {
    id: "am",
    telugu: "అం",
    transliteration: "am",
    englishHint: "Like 'um' in 'hum'",
    mnemonic: "Add a nasal 'mmm' to అ — like humming 🐝",
    audioUrl: "/audio/vowels/am.mp3",
    anchorWord: "అంగడి",
    anchorTransliteration: "ANGADI",
    anchorMeaning: "Shop",
    anchorEmoji: "🏪",
    anchorImage: "/images/anchors/am.png",
  },
  {
    id: "aha",
    telugu: "అః",
    transliteration: "aha",
    englishHint: "Like 'aha' with a breathy end",
    mnemonic: "Say 'ah' then breathe out — 'ahh-ha'",
    audioUrl: "/audio/vowels/aha.mp3",
    anchorWord: "దుఃఖం",
    anchorTransliteration: "DUHKHAM",
    anchorMeaning: "Sadness",
    anchorEmoji: "😢",
    anchorImage: "/images/anchors/aha.png",
  },
];
