import type { DecodableWord } from "@/types";

export const words: DecodableWord[] = [
  {
    id: "amma",
    telugu: "అమ్మ",
    transliteration: "amma",
    meaning: "mother",
    syllables: ["అ", "మ్మ"],
    difficulty: 1,
    requiredLetters: ["a", "ma"],
  },
  {
    id: "nanna",
    telugu: "నాన్న",
    transliteration: "naanna",
    meaning: "father",
    syllables: ["నా", "న్న"],
    difficulty: 1,
    requiredLetters: ["naa", "na"],
  },
  {
    id: "akka",
    telugu: "అక్క",
    transliteration: "akka",
    meaning: "elder sister",
    syllables: ["అ", "క్క"],
    difficulty: 1,
    requiredLetters: ["a", "ka"],
  },
  {
    id: "anna",
    telugu: "అన్న",
    transliteration: "anna",
    meaning: "elder brother",
    syllables: ["అ", "న్న"],
    difficulty: 1,
    requiredLetters: ["a", "na"],
  },
  {
    id: "illu",
    telugu: "ఇల్లు",
    transliteration: "illu",
    meaning: "house",
    syllables: ["ఇ", "ల్లు"],
    difficulty: 2,
    requiredLetters: ["i", "la", "u"],
  },
  {
    id: "pani",
    telugu: "పని",
    transliteration: "pani",
    meaning: "work",
    syllables: ["ప", "ని"],
    difficulty: 2,
    requiredLetters: ["pa", "ni"],
  },
  {
    id: "neeru",
    telugu: "నీరు",
    transliteration: "niiru",
    meaning: "water",
    syllables: ["నీ", "రు"],
    difficulty: 2,
    requiredLetters: ["nii", "ru"],
  },
  {
    id: "cheppu",
    telugu: "చెప్పు",
    transliteration: "cheppu",
    meaning: "slipper/shoe",
    syllables: ["చె", "ప్పు"],
    difficulty: 3,
    requiredLetters: ["che", "pa", "u"],
  },
];
