export const WORD_CATEGORIES = [
  {
    id: "home",
    teluguTitle: "ఇంటి వస్తువులు",
    englishTitle: "Home Items",
    emoji: "🏠",
    words: [
      { te: "ఇల్లు", trans: "ILLU", en: "House", emoji: "🏠" },
      { te: "తలుపు", trans: "THALUPU", en: "Door", emoji: "🚪" },
      { te: "కిటికీ", trans: "KITIKEE", en: "Window", emoji: "🪟" },
      { te: "మంచం", trans: "MANCHAM", en: "Bed", emoji: "🛏️" },
      { te: "కుర్చీ", trans: "KURCHEE", en: "Chair", emoji: "🪑" },
      { te: "బల్ల", trans: "BALLA", en: "Table", emoji: "🪵" },
      { te: "అద్దం", trans: "ADDAM", en: "Mirror", emoji: "🪞" },
      { te: "దీపం", trans: "DEEPAM", en: "Lamp", emoji: "🪔" },
      { te: "గడియారం", trans: "GADIYAARAM", en: "Clock", emoji: "🕐" },
      { te: "చాప", trans: "CHAAPA", en: "Mat", emoji: "🧶" },
      { te: "గొడుగు", trans: "GODUGU", en: "Umbrella", emoji: "☂️" },
      { te: "చెప్పులు", trans: "CHEPPULU", en: "Slippers", emoji: "🩴" },
    ],
  },
  {
    id: "food",
    teluguTitle: "తిండి",
    englishTitle: "Food",
    emoji: "🍎",
    words: [
      { te: "అన్నం", trans: "ANNAM", en: "Rice", emoji: "🍚" },
      { te: "పప్పు", trans: "PAPPU", en: "Lentils/Dal", emoji: "🥘" },
      { te: "సాంబారు", trans: "SAMBAARU", en: "Sambar", emoji: "🍲" },
      { te: "దోశ", trans: "DOSHA", en: "Dosa", emoji: "🥞" },
      { te: "ఇడ్లీ", trans: "IDLEE", en: "Idli", emoji: "⚪" },
      { te: "చపాతీ", trans: "CHAPAATHEE", en: "Chapati", emoji: "🫓" },
      { te: "పెరుగు", trans: "PERUGU", en: "Curd/Yogurt", emoji: "🥛" },
      { te: "పాలు", trans: "PAALU", en: "Milk", emoji: "🥛" },
      { te: "నీళ్ళు", trans: "NEELLU", en: "Water", emoji: "💧" },
      { te: "అరటి పండు", trans: "ARATI PANDU", en: "Banana", emoji: "🍌" },
      { te: "మామిడి పండు", trans: "MAAMIDI PANDU", en: "Mango", emoji: "🥭" },
      { te: "పులిహోర", trans: "PULIHORA", en: "Tamarind rice", emoji: "🍚" },
      { te: "లడ్డు", trans: "LADDU", en: "Laddu sweet", emoji: "🟡" },
      { te: "పకోడీ", trans: "PAKODEE", en: "Pakodi/fritter", emoji: "🧆" },
      { te: "చాయ్", trans: "CHAAY", en: "Tea", emoji: "☕" },
    ],
  },
  {
    id: "animals",
    teluguTitle: "జంతువులు",
    englishTitle: "Animals",
    emoji: "🐾",
    words: [
      { te: "కుక్క", trans: "KUKKA", en: "Dog", emoji: "🐕" },
      { te: "పిల్లి", trans: "PILLI", en: "Cat", emoji: "🐈" },
      { te: "ఆవు", trans: "AAVU", en: "Cow", emoji: "🐄" },
      { te: "గుర్రం", trans: "GURRAM", en: "Horse", emoji: "🐴" },
      { te: "ఏనుగు", trans: "ENUGU", en: "Elephant", emoji: "🐘" },
      { te: "కోతి", trans: "KOTHI", en: "Monkey", emoji: "🐒" },
      { te: "చేప", trans: "CHEPA", en: "Fish", emoji: "🐟" },
      { te: "పాము", trans: "PAAMU", en: "Snake", emoji: "🐍" },
      { te: "కోడి", trans: "KODI", en: "Chicken", emoji: "🐓" },
      { te: "మేక", trans: "MEKA", en: "Goat", emoji: "🐐" },
      { te: "చిలుక", trans: "CHILUKA", en: "Parrot", emoji: "🦜" },
      { te: "కాకి", trans: "KAAKI", en: "Crow", emoji: "🐦⬛" },
    ],
  },
  {
    id: "family",
    teluguTitle: "కుటుంబం",
    englishTitle: "Family",
    emoji: "👨‍👩‍👧",
    words: [
      { te: "అమ్మ", trans: "AMMA", en: "Mother", emoji: "👩" },
      { te: "నాన్న", trans: "NAANNA", en: "Father", emoji: "👨" },
      { te: "అక్క", trans: "AKKA", en: "Elder sister", emoji: "👧" },
      { te: "అన్న", trans: "ANNA", en: "Elder brother", emoji: "👦" },
      { te: "తమ్ముడు", trans: "THAMMUDU", en: "Younger brother", emoji: "👦" },
      { te: "చెల్లి", trans: "CHELLI", en: "Younger sister", emoji: "👧" },
      { te: "తాత", trans: "THAATHA", en: "Grandfather", emoji: "👴" },
      { te: "అమ్మమ్మ", trans: "AMMAMMA", en: "Grandmother (maternal)", emoji: "👵" },
      { te: "నానమ్మ", trans: "NAANAMMA", en: "Grandmother (paternal)", emoji: "👵" },
      { te: "బాబు", trans: "BAABU", en: "Baby/child (boy)", emoji: "👶" },
    ],
  },
  {
    id: "colors",
    teluguTitle: "రంగులు",
    englishTitle: "Colors",
    emoji: "🎨",
    words: [
      { te: "ఎరుపు", trans: "ERUPU", en: "Red", emoji: "🔴" },
      { te: "నీలం", trans: "NEELAM", en: "Blue", emoji: "🔵" },
      { te: "పచ్చ", trans: "PACHCHA", en: "Green", emoji: "🟢" },
      { te: "పసుపు", trans: "PASUPU", en: "Yellow", emoji: "🟡" },
      { te: "తెలుపు", trans: "THELUPU", en: "White", emoji: "⚪" },
      { te: "నలుపు", trans: "NALUPU", en: "Black", emoji: "⚫" },
      { te: "నారింజ", trans: "NAARINJA", en: "Orange", emoji: "🟠" },
      { te: "గులాబీ", trans: "GULAABEE", en: "Pink", emoji: "🩷" },
      { te: "ఊదా", trans: "OODAA", en: "Purple", emoji: "🟣" },
      { te: "బంగారం రంగు", trans: "BANGAARAM RANGU", en: "Gold color", emoji: "✨" },
    ],
  },
  {
    id: "numbers",
    teluguTitle: "సంఖ్యలు",
    englishTitle: "Numbers",
    emoji: "🔢",
    words: [
      { te: "ఒకటి", trans: "OKATI", en: "One (1)", emoji: "1️⃣" },
      { te: "రెండు", trans: "RENDU", en: "Two (2)", emoji: "2️⃣" },
      { te: "మూడు", trans: "MOODU", en: "Three (3)", emoji: "3️⃣" },
      { te: "నాలుగు", trans: "NAALUGU", en: "Four (4)", emoji: "4️⃣" },
      { te: "అయిదు", trans: "AYIDU", en: "Five (5)", emoji: "5️⃣" },
      { te: "ఆరు", trans: "AARU", en: "Six (6)", emoji: "6️⃣" },
      { te: "ఏడు", trans: "EDU", en: "Seven (7)", emoji: "7️⃣" },
      { te: "ఎనిమిది", trans: "ENIMIDI", en: "Eight (8)", emoji: "8️⃣" },
      { te: "తొమ్మిది", trans: "THOMMIDI", en: "Nine (9)", emoji: "9️⃣" },
      { te: "పది", trans: "PADHI", en: "Ten (10)", emoji: "🔟" },
    ],
  },
  {
    id: "nature",
    teluguTitle: "ప్రకృతి",
    englishTitle: "Nature",
    emoji: "🌳",
    words: [
      { te: "చెట్టు", trans: "CHETTU", en: "Tree", emoji: "🌳" },
      { te: "పూలు", trans: "POOLU", en: "Flowers", emoji: "🌸" },
      { te: "ఆకు", trans: "AAKU", en: "Leaf", emoji: "🍃" },
      { te: "సూర్యుడు", trans: "SOORYUDU", en: "Sun", emoji: "☀️" },
      { te: "చంద్రుడు", trans: "CHANDRUDU", en: "Moon", emoji: "🌙" },
      { te: "నక్షత్రం", trans: "NAKSHATHRAM", en: "Star", emoji: "⭐" },
      { te: "వర్షం", trans: "VARSHAM", en: "Rain", emoji: "🌧️" },
      { te: "గాలి", trans: "GAALI", en: "Wind", emoji: "💨" },
      { te: "నది", trans: "NADHI", en: "River", emoji: "🏞️" },
      { te: "కొండ", trans: "KONDA", en: "Mountain", emoji: "⛰️" },
      { te: "సముద్రం", trans: "SAMUDRAM", en: "Ocean", emoji: "🌊" },
      { te: "ఆకాశం", trans: "AAKAASHAM", en: "Sky", emoji: "🌤️" },
    ],
  },
  {
    id: "clothes",
    teluguTitle: "బట్టలు",
    englishTitle: "Clothes",
    emoji: "👕",
    words: [
      { te: "చొక్కా", trans: "CHOKKAA", en: "Shirt", emoji: "👕" },
      { te: "లంగా", trans: "LANGAA", en: "Skirt/Lehenga", emoji: "👗" },
      { te: "చీర", trans: "CHEERA", en: "Saree", emoji: "🥻" },
      { te: "పంచ", trans: "PANCHA", en: "Dhoti", emoji: "🩲" },
      { te: "టోపీ", trans: "TOPEE", en: "Hat/Cap", emoji: "🧢" },
      { te: "చెప్పులు", trans: "CHEPPULU", en: "Slippers", emoji: "🩴" },
      { te: "బూట్లు", trans: "BOOTLU", en: "Shoes", emoji: "👟" },
      { te: "గొడుగు", trans: "GODUGU", en: "Umbrella", emoji: "☂️" },
      { te: "గాజులు", trans: "GAAJULU", en: "Bangles", emoji: "💫" },
      { te: "దండ", trans: "DANDA", en: "Necklace/garland", emoji: "📿" },
    ],
  },
];
